In [1]:
from keras.layers import Input, Lambda, Dense, Flatten
from keras.models import Model
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
import numpy as np
from glob import glob
import matplotlib.pyplot as plt

In [2]:
IMAGE_SIZE = [224, 224]

train_path = 'maleria_cell_images/train'
valid_path = 'maleria_cell_images/test'


In [3]:
vgg = VGG16(input_shape=IMAGE_SIZE + [3], weights='imagenet', include_top=False)

In [4]:
for layer in vgg.layers:
    layer.trainable = False

In [5]:
folders = glob('maleria_cell_images/train/*')

In [6]:
x = Flatten()(vgg.output)

In [7]:
prediction = Dense(len(folders), activation='softmax')(x)

model = Model(inputs=vgg.input, outputs=prediction)

In [8]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [9]:
model.compile(
  loss='categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy']
)


In [10]:
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

In [17]:
train= train_datagen.flow_from_directory('maleria_cell_images/train',
                                                 target_size = (224, 224),
                                                 batch_size = 3,
                                                 class_mode = 'categorical')

Found 416 images belonging to 2 classes.


In [18]:
test = test_datagen.flow_from_directory('maleria_cell_images/test',
                                            target_size = (224, 224),
                                            batch_size = 3,
                                            class_mode = 'categorical')

Found 134 images belonging to 2 classes.


In [19]:
r = model.fit_generator(
  train,
  validation_data=test,
  epochs=5,
  steps_per_epoch=len(train),
  validation_steps=len(test)
)

Epoch 1/5
139/139 [==============================] - 151s 1s/step - loss: 1.0447 - accuracy: 0.7115 - val_loss: 0.3416 - val_accuracy: 0.8657
Epoch 2/5
139/139 [==============================] - 148s 1s/step - loss: 0.6611 - accuracy: 0.7764 - val_loss: 0.4047 - val_accuracy: 0.8284
Epoch 3/5
139/139 [==============================] - 156s 1s/step - loss: 0.5080 - accuracy: 0.8149 - val_loss: 0.6484 - val_accuracy: 0.7463
Epoch 4/5
139/139 [==============================] - 161s 1s/step - loss: 0.3800 - accuracy: 0.8582 - val_loss: 0.9503 - val_accuracy: 0.6940
Epoch 5/5
139/139 [==============================] - 180s 1s/step - loss: 0.3935 - accuracy: 0.8582 - val_loss: 3.6634 - val_accuracy: 0.4403


In [ ]:
# plt.plot(r.history['loss'], label='train loss')
# plt.plot(r.history['val_loss'], label='val loss')
# plt.legend()
# plt.show()
# plt.savefig('LossVal_loss')

In [23]:
import tensorflow as tf

from keras.models import load_model

model.save('maleria2.h5')

In [29]:
# from keras.models import load_model
# from keras.preprocessing import image
# from keras.applications.vgg16 import preprocess_input
# import numpy as np
# model=load_model('pneumonia_model.h5')
import glob
path1='./maleria_cell_images/train/Parasite/C33P1thinF_IMG_20150619_114756a_cell_179.png'
path2='./maleria_cell_images/train/Parasite/C33P1thinF_IMG_20150619_114756a_cell_180.png'
path3='./maleria_cell_images/train/uninfected/C1_thinF_IMG_20150604_104722_cell_9.png'
path4='./maleria_cell_images/train/uninfected/C1_thinF_IMG_20150604_104722_cell_73.png'
uninfected=glob.glob("./maleria_cell_images/train/uninfected/*.png")
infected=glob.glob("./maleria_cell_images/train/Parasite/*.png")

In [36]:
for i in infected:
    img=image.load_img(i,target_size=(224,224))
    x=image.img_to_array(img)
    x=np.expand_dims(x,axis=0)
    img_data=preprocess_input(x)
    classes=model.predict(img_data)
    print(classes)

[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.0000000e+00 3.0359001e-15]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[9.9999988e-01 1.0978496e-07]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[4.993479e-12 1.000000e+00]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[9.0585925e-20 1.0000000e+00]]
[[1.0000000e+00 1.2448436e-14]]
[[1. 0.]]
[[1.0000000e+00 3.7687583e-27]]
[[1. 0.]]
[[1. 0.]]
[[1.000000e+00 1.300531e-28]]
[[3.692047e-26 1.000000e+00]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.6445433e-31 1.0000000e+00]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.0000000e+00 3.5103342e-10]]
[[1. 0.]]
[[1.0000000e+00 2.3300544e-27]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.000000e+00 1.848643e-31]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[3.7822034e-23 1.0000000e+00]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[

In [35]:
int(classes[0][0]) is uninfected

0

In [39]:
classes[0][0]

1.0

In [24]:
uninfected

NameError: name 'uninfected' is not defined

In [40]:
np.argmax(classes, axis=1)

array([0], dtype=int64)